name: PR Merged

on:
  workflow_dispatch:
  pull_request:
    types: [closed]
    branches:
      - main

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: false

jobs:
  deploy-main:
    name: Deploy changes to main in dev AWS account

    permissions:
      id-token: write
      contents: read

    strategy:
      max-parallel: 1
      matrix:
        component: [dnsroot]

    uses: ./.github/workflows/trigger_internal_repo_build.yaml
    secrets: inherit
    with:
      release_version: main
      tf_environment: "main"
      tf_group: "nhs-notify-dns-dev"
      tf_component: ${{ matrix.component }}
      tf_action: "apply"
